version: '3'
services:
  node-1:
    image: redis:latest
    container_name: node-1
    command: ["/redis-server.sh"]
    volumes:
      - ./config/redis-server.sh:/redis-server.sh
      - node-1:/data
  node-2:
    image: redis:latest
    container_name: node-2
    command: ["/redis-server.sh"]
    volumes:
      - ./config/redis-server.sh:/redis-server.sh
      - node-2:/data
    ports:
      - "7002:7000"
  node-3:
    image: redis:latest
    container_name: node-3
    command: ["/redis-server.sh"]
    volumes:
      - ./config/redis-server.sh:/redis-server.sh
      - node-3:/data
  node-4:
    image: redis:latest
    container_name: node-4
    command: ["/redis-server.sh"]
    volumes:
      - ./config/redis-server.sh:/redis-server.sh
      - node-4:/data
  node-5:
    image: redis:latest
    container_name: node-5
    command: ["/redis-server.sh"]
    volumes:
      - ./config/redis-server.sh:/redis-server.sh
      - node-5:/data
  node-6:
    image: redis:latest
    container_name: node-6
    command: ["/redis-server.sh"]
    volumes:
      - ./config/redis-server.sh:/redis-server.sh
      - node-6:/data
  cluster-creator:
    image: redis:latest
    container_name: cluster-creator
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5
      - node-6
    command: redis-cli --cluster create node-1:7000 node-2:7000 node-3:7000 node-4:7000 node-5:7000 node-6:7000 --cluster-replicas 1 --cluster-yes
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/db
    depends_on:
      - cluster-creator

volumes:
  redisinsight:
  node-1:
  node-2:
  node-3:
  node-4:
  node-5:
  node-6: